services:
  # live-reload-air:
  #   image: cosmtrek/air
  #   # working_dir value has to be the same of mapped volume
  #   working_dir: /project-package
  #   ports:
  #     - 3030:3030
  #   volumes:
  #     - ./:/project-package/
#  api:
#    container_name: gitbyeo-api
#    image: janghanul090801/gitbyeo-api:latest
#    ports:
#      - "8000:8000"
#    restart: always
#    env_file:
#      - ./.env
#    depends_on:
#      - postgres

  postgres:
    image: postgres:17
    container_name: postgres
    ports:
      - 5433:5432
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    volumes:
      - ./tmp/db-data:/var/lib/postgresql/data

